// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTvFwTgHFaMnOK1nLUPkHtkeKL-kbdyA',
    appId: '1:328517508690:web:bd6519ec3407e3a635c98b',
    messagingSenderId: '328517508690',
    projectId: 'reciftauthentication',
    authDomain: 'reciftauthentication.firebaseapp.com',
    storageBucket: 'reciftauthentication.appspot.com',
    measurementId: 'G-6BQN0NE4RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrruWmrVPt2nujOzv-_gL73onVMQkUhM',
    appId: '1:328517508690:android:be4adb0cacb3fc1235c98b',
    messagingSenderId: '328517508690',
    projectId: 'reciftauthentication',
    storageBucket: 'reciftauthentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdnl5jX72LVrBky-2nZKWCujOLnaNb0Zw',
    appId: '1:328517508690:ios:d27bef101c21724935c98b',
    messagingSenderId: '328517508690',
    projectId: 'reciftauthentication',
    storageBucket: 'reciftauthentication.appspot.com',
    iosBundleId: 'com.example.cookingrecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdnl5jX72LVrBky-2nZKWCujOLnaNb0Zw',
    appId: '1:328517508690:ios:d27bef101c21724935c98b',
    messagingSenderId: '328517508690',
    projectId: 'reciftauthentication',
    storageBucket: 'reciftauthentication.appspot.com',
    iosBundleId: 'com.example.cookingrecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuTvFwTgHFaMnOK1nLUPkHtkeKL-kbdyA',
    appId: '1:328517508690:web:8412740fe1da026535c98b',
    messagingSenderId: '328517508690',
    projectId: 'reciftauthentication',
    authDomain: 'reciftauthentication.firebaseapp.com',
    storageBucket: 'reciftauthentication.appspot.com',
    measurementId: 'G-252J4KZJNP',
  );
}
